<?php

/** @var Hyva\CheckoutDotdigitalgroupSms\Magewire\ShippingForm $magewire */
?>

<form
    novalidate
    x-data="initDotdigitalSmsValidationForm($el, $wire)"
    @submit.prevent="shippingFormSubmit"
    wire:id="checkout.shipping-details.shipping-phone.form"
>

    <input x-model="addressId" name="addressId" hidden/>
    <div class="w-full font-medium text-gray-700 relative required" x-show="!isValid">

        <div class="w-full px-3 pt-4 mb-6 md:mb-2" wire:ignore.self>
            <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
                   for="dotdigital-shipping-phone-number">
                <?= __('Phone Number') ?>
            </label>

            <input
                id="dotdigital-shipping-phone-number"
                x-intl-input
                x-model="phoneNumber"
                class="block w-full form-input grow renderer-text telephone"
                name="phoneNumber"
                data-validate="{&quot;validate-phone-number&quot: true, &quot;required&quot: true}"
            >
            <div class="w-full pt-3 gap-2 items-center">
                <p id="helper-marketing-consent-text" class="font-normal text-gray-500 dark:text-gray-300"></p>
            </div>
        </div>

    </div>

    <div class="w-full px-3">
        <?= $block->getChildHtml('hyva-checkout-marketing-consent') ?>
    </div>

    <div class="flex flex-col-reverse md:flex-row gap-y-2 md:gap-x-2 w-full justify-end md:items-center">
        <button type="submit" class="btn btn-primary btn-next">
            <?= __('Save / Update') ?>
        </button>
    </div>

</form>
<?= $block->getChildHtml('hyva-checkout-sms-form-js') ?>
