<?php

/** @var Hyva\CheckoutDotdigitalgroupSms\Magewire\MarketingConsent $magewire */
/** @var Magento\Framework\View\Element\Template $block */

/**
 * This section is used to collect and validate the marketing consent information.
 * It uses Alpine.js for the front-end and Livewire for the back-end.
 * The section includes a checkbox for the marketing consent and an input for the phone number.
 * The section data is handled by the Alpine.js instance.
 */
?>

<div wire:id="checkout.marketing-consent">
    <?php if ($magewire->shouldDisplay()): ?>
    <form
        novalidate
        class="col-span-12 field-wrapper field-type-tel field field-reserved field-telephone md:col-span-6"
        @submit.prevent="submit"
        wire:submit.prevent="submit"
        x-data="initDotdigitalSmsValidation($el, $wire)">
        <?= $block->getChildHtml('hyva-checkout-sms-consent-fields') ?>
    </form
    <?php endif; ?>
</div>
