<?php

/** @var Hyva\CheckoutDotdigitalgroupSms\Magewire\ShippingForm $magewire */

/**
 * This form is used to collect and validate the shipping information.
 * It uses Alpine.js for the front-end and Livewire for the back-end.
 * The form includes an input for the phone number and a submit button.
 * The form also includes a hidden input for the address ID and a section for marketing consent.
 * The form data is handled by the `initDotdigitalSmsValidationForm` function and the `shippingFormSubmit` method.
 */
?>


<?php if ($magewire->isCustomerLoggedIn()): ?>
<form
    novalidate
    x-data="{
        ...initDotdigitalSmsValidationForm($el, $wire),
        phoneNumber: <?= $magewire->phoneNumber ?>,
    }"
    @submit.prevent="shippingFormSubmit"
    wire:id="checkout.shipping-details.shipping-phone.form"
    wire:submit.prevent="shippingFormSubmit"
>
    <!-- Hidden input for the address ID -->
    <input x-model="addressId" name="addressId" hidden/>

    <?php if (!$magewire->isValid): ?>
    <!-- Phone number input section -->
    <div class="w-full font-medium text-gray-700 relative required">
        <div class="w-full px-3 pt-4 mb-6 md:mb-2" >
            <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
                   for="dotdigital-shipping-phone-number">
                <?= __('Phone Number') ?>
            </label>

            <div class="flex items-center gap-4 pt-4">
                <div class="w-full gap-2 items-center">
                    <input
                        name="phoneNumber"
                        id="dotdigital-shipping-phone-number"
                        x-intl-input
                        x-model="phoneNumber"
                        class="block w-full form-input grow renderer-text telephone"
                        data-validate="{&quot;validate-phone-number-with-checkbox&quot;: true, &quot;required&quot;: true}"/>
                </div>
            </div>
        </div>
    </div>
    <?php endif; ?>

    <!-- Marketing consent section -->
    <div class="w-full px-3">
        <?= $block->getChildHtml('hyva-checkout-marketing-consent-customer') ?>
    </div>

</form>

<!-- Additional JavaScript for the form -->
<?= $block->getChildHtml('hyva-checkout-sms-form-js') ?>
<?php endif; ?>
