<?php

/** @var Hyva\CheckoutDotdigitalgroupSms\Magewire\ShippingForm $magewire */

/**
 * This form is used to collect and validate the shipping information.
 * It uses Alpine.js for the front-end and Livewire for the back-end.
 * The form includes an input for the phone number and a submit button.
 * The form also includes a hidden input for the address ID and a section for marketing consent.
 * The form data is handled by the `initDotdigitalSmsValidationForm` function and the `shippingFormSubmit` method.
 */
?>
<form
    novalidate
    x-data="initDotdigitalSmsValidationForm($el, $wire)"
    @submit.prevent="shippingFormSubmit"
    wire:id="checkout.shipping-details.shipping-phone.form"
    wire:submit.prevent="shippingFormSubmit"
>
    <?php if($magewire->isCustomerLoggedIn()): ?>
    <!-- Hidden input for the address ID -->
    <input x-model="addressId" name="addressId" hidden/>
    <!-- Phone number input section -->
    <div class="intl-input-wrapper flex flex-col items-center gap-4 pt-4" x-cloak x-show.important="!isValid">

        <div class="w-full gap-2 items-center">
            <label for="DotdigialShippingPhoneNumber"
                   class="block text-sm font-medium text-gray-700 dark:text-gray-300">
                <?= $block->escapeHtml(__('Phone Number')) ?>
            </label>
        </div>

        <div class="w-full gap-2 items-center">
            <input
                name="phoneNumber"
                    id="DotdigitalShippingPhoneNumber"
                x-disabled="isValid"
                x-intl-input
                x-model="phoneNumber"
                class="block w-full form-input grow renderer-text telephone"
                data-validate="<?= $magewire->getValidationConfig() ?>"/>
        </div>

    </div>
    <?php endif; ?>
    <!-- Marketing consent section -->
    <div class="w-full pb-4 mb-4 mt-3">
        <?= $block->getChildHtml('hyva-checkout-marketing-consent-customer') ?>
    </div>

    <!-- Additional JavaScript for the form -->
    <?= $block->getChildHtml('hyva-checkout-sms-form-js') ?>

</form>
