<?php

/** @var Hyva\CheckoutDotdigitalgroupSms\Magewire\MarketingConsent $magewire */
?>
<div
    class="col-span-12 field-wrapper field-type-tel field field-reserved field-telephone md:col-span-6"
    wire:id="checkout.marketing-consent"
    x-init="window.dispatchEvent(new CustomEvent('intlInput:loadBySelector', {detail: {selector: '#DotdigialMarketingConsentPhoneNumber' }}))"
    x-data="{
        marketingConsent: '<?= $magewire->getIsSubscribed() ?>',
        marketingConsentPhoneNumber: '<?= $magewire->getStoredMobileNumber() ?>',
        marketingConsentText: '<?= $magewire->getMarketingConsentText() ?>',
        marketingConsentLabel: '<?= $magewire->getMarketingConsentLabel() ?>',
    }">

    <div class="w-full font-medium text-gray-700 relative required">

        <div class="flex items-center">
            <input
                id="marketing-consent"
                type="checkbox"
                class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                x-model="marketingConsent"
                <?php if($magewire->getIsSubscribed()): echo 'checked'; endif; ?>>
            <label
                for="marketing-consent"
                class="ms-2 ml-2 mt-2 text-sm font-medium text-gray-900 dark:text-gray-300">
                <span x-text="marketingConsentLabel"></span>
            </label>
        </div>

        <div class="flex items-center gap-4 pt-4" x-show="marketingConsent">
            <div class="w-full gap-2 items-center">
                <input
                    id="DotdigialMarketingConsentPhoneNumber"
                    :disabled="!marketingConsent"
                    x-model="marketingConsentPhoneNumber"
                    class="block w-full form-input grow renderer-text telephone"
                    type="tel"
                    data-validate="{&quot;validate-phone-number-with-checkbox&quot;: true, &quot;required&quot;: true}"
            </div>
            <div class="w-full pt-3 gap-2 items-center">
                <p id="helper-marketing-consent-text" class="font-normal text-gray-500 dark:text-gray-300">
                    <span x-text="marketingConsentText"></span>
                </p>
            </div>
        </div>

    </div>

</div>
