<?php

/** @var Hyva\CheckoutDotdigitalgroupSms\Magewire\ShippingPhone $magewire */
?>


    <form
        wire:id="checkout.shipping-details.shipping-phone"
        x-show="!isLoading"
        x-data="{
            ...{
                shippingPhoneNumber: '<?= $magewire->phoneNumber ?>',
                addressId: Livewire.find('checkout.shipping-details.address-list').activeAddressEntity,
                isLoading: false
            },
            ...hyva.formValidation($el)
        }"
        @submit="ShippingFormSubmit"
        method="post"
        class="w-full max-w-lg p-4">

        <header class="section-title border-b border-gray-400 pb-1 mt-6">
            <h2 class="text-gray-800 text-xl font-medium">
                <?= __('Phone number and marketing consent') ?>
            </h2>
        </header>

        <div class="flex flex-wrap -mx-3 mb-6">
            <h1> <?=$magewire->isValid; ?></h1>
            <?php if (!$magewire->isValid) : ?>
                <input x-model="addressId" name="addressId" hidden/>
                <div class="w-full px-3 pt-4 mb-6 md:mb-2" wire:ignore.self>
                    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
                           for="DotdigitalShippingPhoneNumber">
                        <?= __('Phone Number') ?>
                    </label>
                    <input
                        wire:model.defer="shippingPhoneNumber"
                        x-init="window.dispatchEvent(new CustomEvent('intlInput:loadBySelector', {detail: {selector: '#DotdigitalShippingPhoneNumber' }}))"
                        id="DotdigitalShippingPhoneNumber"
                        class="block w-full form-input grow renderer-text telephone"
                        name="phoneNumber"
                        data-validate="{&quot;validate-phone-number-with-checkbox&quot: true, &quot;required&quot: true}"
                    >
                </div>
            <?php endif; ?>

<!--            <div class="w-full px-3">-->
<!--                --><?php //= $block->getChildHtml('hyva-checkout-marketing-consent') ?>
<!--            </div>-->

            <div class="flex flex-col-reverse md:flex-row gap-y-2 md:gap-x-2 w-full justify-end md:items-center">
                <button type="submit" class="btn btn-primary btn-next">
                    <?= __('Save / Update') ?>
                </button>
            </div>

        </div>

    </form>

<script>

    window.addEventListener('magewire:load', () => {
        Magewire.hook('element.updated', (el, component) => {
            if (component.id === 'checkout.shipping-details.address-list') {
                Livewire.emit('address_list_updated')
            }
        }, {once: true});
    }, {once: true});


    async function ShippingFormSubmit(event) {
        event.preventDefault()

        const formData = new FormData(this.$el)
        const payload = {}
        for( [key, value] of formData.entries() ) {
            payload[key] = value
        }

        try {
             await this.validate()
        } catch (e) {
            return
        }

        this.$wire.formSubmit(payload)
        Livewire.emit('shipping_phone_number_updated')

    }
</script>
