<?php

declare(strict_types=1);

use Dotdigitalgroup\Sms\ViewModel\Customer\Account\MarketingConsent;
use Dotdigitalgroup\Sms\ViewModel\TelephoneInputConfig;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/**
 * @var Template $block
 * @var TelephoneInputConfig $telephoneInputConfig
 * @var MarketingConsent $consentConfig
 * @var Escaper $escaper
 */

// @codingStandardsIgnoreFile

// Get the telephone input configuration from the block data.
$telephoneInputConfig = $block->getData('telephoneInputConfig');

// Get the consent configuration from the block data.
$consentConfig = $block->getData('consentConfig');

// Check if the phone number should be validated with a checkbox.
if ($consentConfig->shouldValidatePhoneNumberWithCheckbox()) { ?>

    <script type="module">
        // Import the necessary modules and styles.
        import '<?= $escaper->escapeJs($block->getViewFileUrl('Dotdigitalgroup_Sms::js/intlTelInput.js')) ?>';
        import {
            validationRule,
            intlInput,
            includeStyle
        } from '<?= $escaper->escapeJs($block->getViewFileUrl('Hyva_DotdigitalgroupSms::js/intl-input-validation.js')) ?>';
        includeStyle('<?= $escaper->escapeJs($block->getViewFileUrl('Dotdigitalgroup_Sms::css/hyva.css')) ?>');

        // Add the validation rules to the form validation.
        window.addEventListener(
            'alpine:init',
            () => {
                hyva.formValidation.addRule( 'validate-phone-number-with-checkbox', validationRule );
            }
        );

        // Initialize the international telephone input when the checkout step is loaded.
        window.addEventListener(
            'checkout:step:loaded',
            () => intlInput("input[type='tel']", <?= $telephoneInputConfig->getConfig(); ?>)
        );

        Magewire.hook('element.updated', (el, component) => {
            if (component.id === 'checkout.shipping-details.address-form') {
                intlInput("input[type='tel']", <?= $telephoneInputConfig->getConfig(); ?>);
            }
        }, true);

        // Add a directive to the Alpine.js instance for the international telephone input.
        document.addEventListener('alpine:init', () => {

            Alpine.directive('intl-input',(el, props, {effect, cleanup}) => {

                const config = {
                    ...<?= $telephoneInputConfig->getConfig(); ?>,
                    ...props.expression
                };



                effect(() => {
                    const parent = el.closest('.field-reserved');
                    console.log(parent);

                    if (!window.intlTelInput) return console.warn('intlTelInput is not loaded')
                    if (!window.intlTelInputGlobals) return console.warn('intlTelInputGlobals is not loaded')
                    window.intlTelInput(el, config);
                });

                cleanup(() => {
                    delete window.intlTelInput(el);
                    delete el.intlTelInput;
                });

            });

        });
    </script>
<?php } ?>
