<div x-data="DotdigitalMarketingConsentFormFields">
    <div class="flex flex-col font-medium text-gray-700 relative required">
        <!-- Marketing consent checkbox section -->
        <div class="flex items-center">
            <input
                name="marketingConsent"
                id="marketing-consent"
                type="checkbox"
                class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500
            dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                :value="marketingConsent" @change="checkboxChangeEvent">
            <label
                for="marketing-consent"
                class="ms-2 ml-2 mt-2 text-sm font-medium text-gray-900 dark:text-gray-300">
                <span x-text="marketingConsentLabel"></span>
            </label>
        </div>
        <!-- Phone number input section -->
        <div class="flex flex flex-col items-center gap-4 pt-4" x-show="showMarketingConsent">
            <div class="w-full gap-2 items-center">
                <input
                    name="marketingConsentPhoneNumber"
                    id="DotdigialMarketingConsentPhoneNumber"
                    :disabled="isMarketingConsentDisabled"
                    x-intl-input
                    :value="marketingConsentPhoneNumber" @change="inputChangeEvent"
                    class="block w-full form-input grow renderer-text telephone"
                    data-validate="{&quot;validate-phone-number-with-checkbox&quot;: true, &quot;required&quot;: true}">
            </div>
            <!-- Marketing consent text section -->
            <div class="w-full pt-3 gap-2 items-center">
                <p id="helper-marketing-consent-text" class="font-normal text-gray-500 dark:text-gray-300">
                    <span x-text="marketingConsentText"></span>
                </p>
            </div>
        </div>
    </div>
</div>
