<script>

    /**
     * This function initializes the shipping form validation.
     *
     * @param {HTMLFormElement} form - The form element to be validated.
     * @param {LivewireComponent} wire - The Livewire component instance.
     * @returns {Object} - Returns an object with the form validation methods and properties.
     */
    function initDotdigitalSmsValidationForm(form, wire) {

        // Find the address list component in the Livewire instance.
        const address_list = Livewire.find('checkout.shipping-details.address-list')

        /**
         * This function checks if the selected shipping address is valid.
         *
         * @param {HTMLFormElement} form - The form element to be validated.
         * @returns {Promise<boolean>} - Returns a promise that resolves to a boolean indicating the validity of the form.
         */
        const checkSelectedShippingAddressValid = async ( form ) => {
            try {
                await form.validate()
            } catch (e) {
                wire.updateValidity(false)
                await wire.refresh()
                return false
            }
            wire.updateValidity(true)
            await wire.refresh()
        }

        /**
         * This function collects the form data and returns it as an object.
         *
         * @param {HTMLFormElement} form - The form element to collect data from.
         * @returns {Object} - Returns an object with the form data.
         */
        const collectFormData = (form) => {
            const payload = {}
            for ([key, value] of  new FormData(form).entries()) {
                payload[key] = value
            }
            return payload
        }

        // Return an object with the form validation methods and properties.
        return Object.assign(
            {},
            hyva.formValidation(form),
            {
                isValid: wire.entangle('isValid'),
                phoneNumber: wire.phoneNumber,
                addressId: address_list.activeAddressEntity
            },
            {
                init(){
                    /**
                     * This step will add a new listener to the navigation to validate and submit the shipping form
                     * when the user navigates to the next step.
                     */
                    hyvaCheckout.navigation.addTask(() => this.shippingFormSubmit())

                    /**
                     * This step will check if the selected shipping address is valid when the form is loaded.
                     */
                    this.$nextTick(() => checkSelectedShippingAddressValid(this))

                    /**
                     * This step will refresh the shipping form when the address list is updated.
                     */
                    Magewire.hook('element.updated', (el, component) => {
                        if (component.id === 'checkout.shipping-details.address-list') {
                            wire.refresh()
                        }
                    });
                },

                /**
                 * This method will submit the shipping form.
                 *
                 * @param {Event} event - The event object.
                 * @returns {Promise<boolean>} - Returns a promise that resolves to a boolean indicating the success of the form submission.
                 */
                async shippingFormSubmit(event) {
                    const payload = collectFormData(this.$el)
                    try {
                        await this.validate()
                    } catch (e) {
                        return false
                    }

                    await wire.shippingFormSubmit(payload)
                    await wire.refresh()
                },


            })
    }
</script>
